### ISSUE TITLE
Feedback?

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/mregions#1]
@ahjones1 @remsamp @samuelbosch @pieterprovoost @tomjwebb 

just pinging you for any feedback, open issues as needed for bugs, features, etc.

**Comment by wardappeltans** [comment]
this is great Scott!! 

Is there an r package to the World Protected Area Database? I would like to access OBIS by marine protected area based on the polygones available at 
https://github.com/unepwcmc/ProtectedPlanet

**Comment by sckott** [comment]
I do t know about that data source. I'll check

**Comment by sckott** [comment]
thanks @wardappeltans , as you saw https://github.com/sckott/rwdpa started, so closing this
