### ISSUE TITLE
add geocoding

### ISSUE THREAD

**Issue by pieterprovoost** [ropenscilabs/mregions#11]
http://www.marineregions.org/rest/getGazetteerRecordsByName.json/oosterschelde/true/false/

**Comment by sckott** [comment]
thanks!, will do

**Comment by sckott** [comment]
@pieterprovoost Do you know who I can ask about the marineregions API?

There seems to be weird behavior with the query parameters - e.g. 

http://www.marineregions.org/rest/getGazetteerRecordsByName.json/oost/false/true/ gives 200 response but no content back

http://www.marineregions.org/rest/getGazetteerRecordsByName.json/oost/false/false/ gives 200 response but no content back 

It's rather unclear what to make of these responses. 200 status indicates no problems, but why nothing returned?  usually no body reserved for responses to `DELETE` requests

**Comment by pieterprovoost** [comment]
Yes, that seems to be a bug. Maybe ask @bart-v

**Comment by bart-v** [comment]
It's not a bug, empty just means no result.

What is the standard to return for no results?
Something like this:
- "" - For a string field
- [] - For an array field
- {} - For an object field

http://programmers.stackexchange.com/questions/199742/restful-api-design-what-should-i-return-if-there-are-no-rows

**Comment by pieterprovoost** [comment]
In case there are results, it returns an array: http://www.marineregions.org/rest/getGazetteerRecordsByName.json/oost/true/true/

So it should return `[]` for no results.

**Comment by bart-v** [comment]
OK, all fixed

**Comment by sckott** [comment]
thanks @pieterprovoost and @bart-v - that helps a lot
