### ISSUE TITLE
put in handling for projected Spatial objects

### ISSUE THREAD

**Issue by mdsumner** [ropenscilabs/mregions#26]
robis::occurrence expects geometry using only longitude/latitude, but as_wkt does not do anything different with a projected Spatial object.

@mdsumner can contribute this

**Comment by sckott** [comment]
thanks!

**Comment by mdsumner** [comment]
Done in 8b95cb02934dcfaa3d9bcf346a59b2d9323a1806 and https://github.com/ropenscilabs/mregions/pull/31
