### ISSUE TITLE
Changing maxFeatures argument in mr_shp?

### ISSUE THREAD

**Issue by tomjwebb** [ropenscilabs/mregions#32]
Hi Scott, I've been playing with the new CRAN version, very impressed but have one issue regarding the maxFeatures argument in mr_shp - I would like to download (for example) a shape file of all 100 or so IHO Sea Areas, but the import is limited to 50:

```
res4 <- mr_shp(key = "MarineRegions:iho")
length(res4$name)
```

gives 50. It looks like I should be able to change this by changing the maxFeatures argument but this doesn't seem to work - I still get 50 regions returned whether I set this argument to 10 or 100, e.g.

```
res4 <- mr_shp(key = "MarineRegions:iho", maxFeatures = 10))
length(res4$name)
```

also gives 50. Am I missing something obvious here? Would be really useful to be able to get the full set of shapes for a given geometry to allow e.g. summarising a species distribution, as records per IHO area, EEZ, or whatever.

Thanks!

**Comment by sckott** [comment]
thanks for your question. I'll have a look

**Comment by sckott** [comment]
@tomjwebb okay, reinstall `devtools::install_github("ropenscilabs/mregions")`

We use caching via `rappdirs` and we were caching just based on the region name (e.g., `iho`) and not including `maxFeatures` if given by the user. Now the function caching includes `maxFeatures`.  That's what I believe was responsible. That you had made a request for data from `iho`, it was cached, and the next call uses that same file, even if you change `maxFeatures`, - it should work now

also, not that changed `readOGR` to use `stringsAsFactors=FALSE`

**Comment by tomjwebb** [comment]
@sckott Speedy as always, and that works perfectly now. Thanks!
