### ISSUE TITLE
WFS versions?

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/mregions#33]
wonder why we are using WFS v1 (http://geo.vliz.be/geoserver/ows?service=wfs&version=1.0.0&request=GetCapabilities) instead of v2 (http://geo.vliz.be/geoserver/ows?service=wfs&version=2.0.0&request=GetCapabilities)

i'm not familiar enough with these 

thoughts? @tomjwebb @mdsumner @pieterprovoost

**Comment by LennertSchepers** [comment]
There are some small differences: https://docs.geoserver.org/stable/en/user/services/wfs/basics.html#differences-between-wfs-versions 
The vliz geoserver (geo.vliz.be) supports three WFS versions: 1.0.0, 1.1.0 and 2.0.0, but I don't think there is a reason to update to 2.0.0 so I'll close this issue.

**Comment by LennertSchepers** [comment]
just noted that several functions already use WFS 2.0.0; #35 added the option of specifying wfs version 1.0.0 in mr_features_get(), and mr_names() also uses WFS 2.0.0
