### ISSUE TITLE
New release of marineregions causing problems

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/mregions#34]

**Comment by sckott** [comment]
@bart-v @pieterprovoost Curious if you have some insight on a problem I'm seeing. 

I see that Marineregions got an update http://www.marineregions.org/news.php?p=show&id=4731 

I assume there were coordinated updates in http://geo.vliz.be/geoserver ? In this package I get marine region names/ids/etc. from geo.vliz.be/geoserver , specifically http://geo.vliz.be/geoserver/ows?service=wfs&version=2.0.0&request=GetCapabilities - There used to be many regions with names like `MarineRegions:eez_33176`, etc. Whereas now there are very few of those. 

The only names with `MarineRegions` I see are 

MarineRegions:eez_archipelagic_waters
MarineRegions:arcticmarineareas
MarineRegions:coasts_subnational
MarineRegions:coasts_per_ocean
MarineRegions:eez_24nm
MarineRegions:comarge
MarineRegions:cross_dateline_polygons
MarineRegions:eez
MarineRegions:fadaregions
MarineRegions:fao
MarineRegions:gsas_mediterraneanfishingzones
MarineRegions:icesecoregions
MarineRegions:ices_ecoregions
MarineRegions:ices_areas
MarineRegions:ices_statistical_rectangles
MarineRegions:iho_quadrants_20150810
MarineRegions:eez_internal_waters
MarineRegions:lme
MarineRegions:longhurst
MarineRegions:eez_land
MarineRegions:eez_iho_union_v2
MarineRegions:eez_boundaries
MarineRegions:ospar_boundaries
MarineRegions:ospar_regions
MarineRegions:seavox_v16
MarineRegions:seavox_sea_area_polygons_v13
MarineRegions:eez_12nm
MarineRegions:world_bay_gulf
MarineRegions:worldheritagemarineprogramme
MarineRegions:world_countries_coasts
MarineRegions:world_estuary_delta

I wonder where the individual eez regions went to in the Geoserver metadata

When I get a shp file for `MarineRegions:eez` there are individual eez reginos in that file

**Comment by sckott** [comment]
fixes to examples and test in 24588e1641683528984c186e34da9cd20aaf436a

**Comment by bart-v** [comment]
Hi @sckott , we never claimed you should use the layers "mrgid_<number>".
These were just (temportary) duplications of what is available in the layer "eez"
http://www.marineregions.org/webservices.php

See here:
You'll just need to use a filter now.
Get the Features > "EEZ Polygons"

**Comment by sckott** [comment]
thanks @bart-v for your help

**Comment by sckott** [comment]
@bart-v is there a way to get just the metadata for regions. that is, `request=GetFeature`  gets the actual features, but I just want metadata for a each region and each feature within a region

**Comment by bart-v** [comment]
Well these are standard OGC WFS calls.
http://docs.geoserver.org/latest/en/user/services/wfs/reference.html

How about something like this?
`http://geo.vliz.be/geoserver/MarineRegions/wfs?service=wfs&version=2.0.0&request=GetFeature&typeNames=MarineRegions:eez&propertyName=mrgid,geoname`

You can output any field by adding it to the `propertyName` parameter

**Comment by sckott** [comment]
thanks very much. i've not experienced much WFS, so thanks for the help

**Comment by pieterprovoost** [comment]
@sckott Do you plan to work on this, or should I try to come up with a solution? I imagine we'll need something like:

```R
# http://geo.vliz.be/geoserver/MarineRegions/wms?Request=getCapabilities
mr_search_layers(q) 

# http://geo.vliz.be/geoserver/MarineRegions/wfs?service=wfs&version=2.0.0&request=GetFeature&typeNames=MarineRegions:eez&propertyName=mrgid,geoname
mr_search_features(q, layer) 

# http://geo.vliz.be/geoserver/MarineRegions/wfs?service=wfs&version=2.0.0&request=GetFeature&typeNames=MarineRegions:eez&featureID=eez.3,eez.4
mr_get_features(q, layer)
```

**Comment by sckott** [comment]
@pieterprovoost thanks for your ping. I did start something but haven't pushed it up yet. Will do so soon and ping you when it's up

**Comment by juanmayorgahenao** [comment]
Hi Guys, I've been running into problems with code I wrote before the update.  For instance:

```
res2 <- mr_shp(name = "Belgian Exclusive Economic Zone")
```` 
gets me an error: Error in strsplit(key, ":")[[1]] : subscript out of bounds. 

Could you point in the right direction on how to fix this? 

Thanks,

**Comment by sckott** [comment]
@juanmayorgahenao Do you mean the update or marineregions.org? Or this package?

I will push some fixes soon.

**Comment by juanmayorgahenao** [comment]
@sckott I mean the update of marineregions.org.

**Comment by pieterprovoost** [comment]
@juanmayorgahenao This is a temporary workaround:

```
res2 <- mr_shp(key = "MarineRegions:eez", filter = "Belgian Exclusive Economic Zone")
```

**Comment by juanmayorgahenao** [comment]
@pieterprovoost Thank you Pieter!

**Comment by sckott** [comment]
Okay, i've implemented `mr_features_get()` function, reinstall `devtools::install_github("ropenscilabs/mregions")`

let me know if it seems good, or if suggestions for changes. 

@petermeissner above you had in your suggestion `mr_get_features(q, layer)` - what is the `layer`  there?

**Comment by pieterprovoost** [comment]
@sckott `layer` would correspond to one of the `featureType` returned from `GetCapabilities`. So:

```R
res <- mr_get_features("Belgian Exclusive Economic Zone", layer = "MarineRegions:eez")
```

The idea was that this would get all features from `MarineRegions:eez` (but just the `geoname` property), find the ones that match `q`, and then do another request to get the full features including the geometry. 

The problem here is that other layers do not have the `geoname` field. For FAO areas for example you would need to fetch the `name` property to look for `Pacific` instead of `geoname`. Maybe that's something that @bart-v can fix.

```R
res <- mr_get_features("Pacific", layer = "MarineRegions:fao")
```

But I haven't looked into your new code yet. Thanks!

**Comment by sckott** [comment]
ah, okay, I think what you are calling `layer` is the same as `typeNames` query parameter, and in the new function `mr_features_get` the parameter is `type`

by the way, where is the `q` parameter defined? is that just available on all endpoints?

**Comment by sckott** [comment]
added new function `mr_layers` to list layers via http://geo.vliz.be/geoserver/MarineRegions/wms?Request=getCapabilities  - but not sure how to do queries on it, is that documented somewhere?

**Comment by juanmayorgahenao** [comment]
Hi guys, I'm having trouble finding some EEZ. Before, I could take a look at EEZs with `mregions::mr_names()`. What's the current way of doing this?  
For example I'm looking for the EEZ of  Brazil but `mr_shp(key = "MarineRegions:eez", filter = "Brazilian Exclusive Economic Zone")` can't find the eez. Thanks in advance

**Comment by sckott** [comment]
@juanmayorgahenao reinstall, then see `mr_names2` - not complete yet, and name may change

**Comment by sckott** [comment]
i have to get a new version to CRAN (https://github.com/ropenscilabs/mregions/milestone/3) as they're getting mad at me due to breaking tests due to marineregions changes, will get to proper fixes in the next version (v0.2) to hit CRAN

**Comment by juanmayorgahenao** [comment]
Hi Guys, I'm having trouble again obtaining EEZ shapfiles for some countries. For example, when I do `mexico_eez_pacific <- mregions::mr_shp(
  key = "MarineRegions:eez",
  filter = "Mexican Exclusive Economic Zone"
)` I get no data back. Is there a current work around to this problem? Thanks in advance

**Comment by sckott** [comment]
see the `maxFeatures` parameter, e.g.., 

```r
mregions::mr_shp(
  key = "MarineRegions:eez", 
  filter = "Mexican Exclusive Economic Zone",
  maxFeatures = 200)
``` 

i don't remember what it was like before, but I guess it didn't do paging before perhaps

**Comment by salvafern** [comment]
I'll close this issue for now as it is already quite old and there has been new releases of the maritime boundaries product since then.
