### ISSUE TITLE
replace httr with crul

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/mregions#36]

**Comment by LennertSchepers** [comment]
Is `crul` still preferred over `httr`? Or is there any other package that is recommended?

**Comment by sckott** [comment]
`crul` is just the package that I maintain - so i know it better than `httr` - up to you now!

**Comment by sckott** [comment]
but those are the two major http pkgs - if you want to go lower level you could go with `curl`

**Comment by maelle** [comment]
maybe even httr2 these days :slightly_smiling_face: https://httr2.r-lib.org/

**Comment by salvafern** [comment]
Hi, I will close this issue following [rOpenSci guidance on archiving packages](https://devguide.ropensci.org/maintenance_evolution.html#archivalguidance)

This repository has been archived and it is replaced by [mregions2](https://docs.ropensci.org/mregions2/). For further details please see: [Why mregions and mregions2?](https://docs.ropensci.org/mregions2/articles/why_mregions2.html).

mregions2 uses httr2 :slightly_smiling_face:
