### ISSUE TITLE
move to using markdown in roxygen docs

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/mregions#38]

**Comment by brooklynbagel** [comment]
This is something I could take a crack at.

**Comment by sckott** [comment]
thanks, sounds good @brooklynbagel 

the markdown vignette is here https://cran.rstudio.com/web/packages/roxygen2/vignettes/markdown.html

**Comment by brooklynbagel** [comment]
Here's the PR @sckott: https://github.com/ropensci/mregions/pull/47
