### ISSUE TITLE
SHAPE-ZIP return type not working with mr_features_get()

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/mregions#39]
apparently that type is just not available anymore

**Comment by bart-v** [comment]
`java.io.FileNotFoundException: /tmp/tomcat7-tomcat7-tmp/shpziptemp0.0574966302897717/isobathes_100m_select.cst (No such file or directory)`

`/dev/sda1          0 100% /`

Duh, fixed, thank for this :)

**Comment by sckott** [comment]
great, thanks!
