### ISSUE TITLE
handle pagination automatically?

### ISSUE THREAD

**Issue by cboettig** [ropenscilabs/mregions#40]
I hate having to manually handle pagination with API wrappers, particularly when it's not obvious how many total records are available.  Can we get an option to do this automatically (like in `gh` package with `limit=Inf`), pretty please?  (e.g. for the `mr_records_by_type` fn, not sure if applies elsewhere).

**Comment by sckott** [comment]
good idea, will look into it - only thing that might affect that is rate limiting, but I don't think there is any

**Comment by salvafern** [comment]
Hi, I will close this issue following [rOpenSci guidance on archiving packages](https://devguide.ropensci.org/maintenance_evolution.html#archivalguidance)

This repository has been archived and it is replaced by [mregions2](https://docs.ropensci.org/mregions2/). For further details please see: [Why mregions and mregions2?](https://docs.ropensci.org/mregions2/articles/why_mregions2.html).

mregions2 handles pagination automatically :slightly_smiling_face:
