### ISSUE TITLE
Error: Client error: (401) Unauthorized

### ISSUE THREAD

**Issue by babycamel** [ropenscilabs/mregions#43]
I'm.  getting this error message with the CRAN version of mregions. Is their a way to fix this?

**Comment by sckott** [comment]
Can you give the output of your `sessionInfo()` please, including what function(s) called that  generated that error

**Comment by babycamel** [comment]
The only output was the error message. The function that generated it initially was mr_place_types()
but other functions generated the same error. I'm checking whether it is a firewall issue at my end.

**Comment by sckott** [comment]
session info please

**Comment by babycamel** [comment]
It was a firewall issue at my end. Sorry to bother you. Wasn't immediately apparent.
