### ISSUE TITLE
transfer to ropensci

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/mregions#45]
since we keep onboarded repos there 😺 

If you transfer it, could you please add an active status badge to the README when updating all links? 🙏 

`[![Project Status: Active – The project has reached a stable, usable state and is being actively developed.](http://www.repostatus.org/badges/latest/active.svg)](http://www.repostatus.org/#active)`

**Comment by sckott** [comment]
fixed i n 8ad9f1aa1309b4ee6acdb5339db6108e311c1fbd

**Comment by maelle** [comment]
🎊
