### ISSUE TITLE
consider using sf instead of sp

### ISSUE THREAD

**Issue by LennertSchepers** [ropenscilabs/mregions#52]
Consider using `sf` instead of `sp`, see question in #42

**Comment by salvafern** [comment]
Hi, I will close this issue following [rOpenSci guidance on archiving packages](https://devguide.ropensci.org/maintenance_evolution.html#archivalguidance)

This repository has been archived and it is replaced by [mregions2](https://docs.ropensci.org/mregions2/). For further details please see: [Why mregions and mregions2?](https://docs.ropensci.org/mregions2/articles/why_mregions2.html).

mregions2 uses sf :slightly_smiling_face:
