### ISSUE TITLE
add remaining/new gazetteer REST services

### ISSUE THREAD

**Issue by LennertSchepers** [ropenscilabs/mregions#54]
Add remaining gazetteer REST services? http://marineregions.org/gazetteer.php?p=webservices, see the question in #42.

Note that we are in the process of updating our web services so there will be new web services added (foreseen summer 2021).

**Comment by pieterprovoost** [comment]
@LennertSchepers Do you have an updated timeline for this? We are specifically looking for geometries by MRGID.

**Comment by LennertSchepers** [comment]
Hi @pieterprovoost 
Yes - actually we have a [working function that retrieves the geometry](https://lifewatch.github.io/mregions2/reference/mr_gaz_record.html), but take into account that the `mregions2` package is still in development so it might change a bit before we release a stable version. Adding @salvafern and @whaleshark99 for more detailed questions.

I will actually close this issue as we will release a new package.

**Comment by LennertSchepers** [comment]
closing
