### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by LennertSchepers** [ropenscilabs/mregions#55]
The documentation of the package could be a bit improved:

- add some general intro about MarineRegions.org
- improve the vignette highlighting some of the key products of MarineRegions (EEZs,...) - remove "Morocco:dam" example
- add a CONTRIBUTING.md ([some](https://github.com/ropensci/wateRinfo/blob/master/.github/CONTRIBUTING.md) [examples](https://github.com/ropensci/skimr/blob/master/.github/CONTRIBUTING.md#understanding-the-scope-of-skimr))
- add roadmap, as an issue or add new [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)

**Comment by martinpastoors** [comment]
Would be nice if you could generate an overview of the different shape files available on MarineRegions, e.g. different types of shapes and different versions of the shape files. This could be included in the documentation.

**Comment by salvafern** [comment]
Listing some ideas:

- [ ] Vignettes: How to work with MR data products: EEZ, Continental Shelves, IHO etc

(I will be editing this comment)

**Comment by salvafern** [comment]
Hi, I will close this issue following [rOpenSci guidance on archiving packages](https://devguide.ropensci.org/maintenance_evolution.html#archivalguidance)

This repository has been archived and it is replaced by [mregions2](https://docs.ropensci.org/mregions2/). For further details please see: [Why mregions and mregions2?](https://docs.ropensci.org/mregions2/articles/why_mregions2.html).

mregions2 has more extensive documentation. If you feel like there is anything missing please [open an issue](https://github.com/ropensci/mregions2/issues/new) over there and I will have a look.
