### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by salvafern** [ropenscilabs/mregions#56]
Hi,

The current license file seems to have been created automatically

https://github.com/ropensci/mregions/blob/ffffd9b6bf28e6f7d160ff55fd9d11f323e828d6/LICENSE

Shall we add a license that allows reuse? Not sure what's the preferred license for ropensci. I saw some packages are released under GNU.

**Comment by LennertSchepers** [comment]
Hi @salvafern 
The license is MIT, see https://github.com/ropensci/mregions/blob/ffffd9b6bf28e6f7d160ff55fd9d11f323e828d6/DESCRIPTION#L9.

The license file mentions the copyright holder and the year, see https://r-pkgs.org/license.html#key-files

**Comment by salvafern** [comment]
Ah ok I see, normally I look at the LICENSE.md file. Thanks.
