### ISSUE TITLE
API OBIS not working: Could not resolve host: api.iobis.org

### ISSUE THREAD

**Issue by salvafern** [ropenscilabs/mregions#57]
Hi @pieterprovoost,

Just ran one of the examples of the documentation and this doesn't work

``` r
library(mregions)
mr_obis_eez_id("bulgarian exclusive economic zone")
#> Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: api.iobis.org
```

<sup>Created on 2022-03-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I tested both on windows and ubuntu, using the latest version of curl. Can you confirm if this is a problem of the OBIS API?

Thanks!

**Comment by pieterprovoost** [comment]
The base URL for the OBIS API is https://api.obis.org/ (not iobis). But I recommend removing OBIS functionality from mregions, if necessary I'll provide a replacement in the robis package.

**Comment by salvafern** [comment]
Ok thanks, we will be working in an update of the package in the following months. We can deprecate this function and maybe move it to robis.

**Comment by salvafern** [comment]
Hi again @pieterprovoost 

Im trying to add a quick fix for this issue. I can see the requests are going towards https://api.obis.org/eez But doesn't seem to exists. 

Is there any equivalent service in the OBIS API? Otherwise I suggest we shut down this function already.

Thanks!

**Comment by pieterprovoost** [comment]
You could use https://api.obis.org/area instead, but again, I recommend removing this from the package. This is totally unrelated to Marine Regions.

**Comment by salvafern** [comment]
I have fixed the issue, but I noticed that https://api.obis.org/area does not include the EEZs, thus the function does not make much sense now. I have removed `mr_obis_eez_id` from mregions. 

The function has not been working for a while and we haven't received any feedback, so I assume it was not being used. If anyone experience a problem, feel free to reopen this issue. 

Thanks for the help @pieterprovoost !
