### ISSUE TITLE
mr_as_wkt() does not accept output sf format of mr_shp()

### ISSUE THREAD

**Issue by lottepohl** [ropenscilabs/mregions#65]
`mr_shp()` from the `mregions` package generates a sf object that `mr_as_wkt()` does not take as input.
Consider https://github.com/ropensci/mregions/issues/52 in https://github.com/lifewatch/mregions2.
``` r
library("mregions")
er_shp <- mr_shp(key = "Ecoregions:ecoregions")
class(er_shp)
#> [1] "sf"         "tbl_df"     "tbl"        "data.frame"
er_wkt <- mr_as_wkt(er_shp)
#> Error: no 'mr_as_wkt' method for sftbl_dftbldata.frame
```

**Comment by salvafern** [comment]
Hi, I will close this issue following [rOpenSci guidance on archiving packages](https://devguide.ropensci.org/maintenance_evolution.html#archivalguidance)

This repository has been archived and it is replaced by [mregions2](https://docs.ropensci.org/mregions2/). For further details please see: [Why mregions and mregions2?](https://docs.ropensci.org/mregions2/articles/why_mregions2.html).
