### ISSUE TITLE
MEOW data

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/mregions#8]
@pieterprovoost @wardappeltans 

Do you know if http://www.marineregions.org/sources.php#meow from Marineregions is in the Geoserver?  I don't see it anywhere.

**Comment by pieterprovoost** [comment]
@sckott http://geo.vliz.be/geoserver/Ecoregions/wms?service=WMS&version=1.1.0&request=GetMap&layers=Ecoregions:ecoregions&styles=&bbox=-180.0,-89.9,180.0,86.919&width=671&height=330&srs=EPSG:4326&format=application/openlayers

**Comment by sckott** [comment]
Thanks. So MEOW is called `ecoregions`  I"m hoping for way to get MEOW regions by name

**Comment by sckott** [comment]
sorted out now
